import type { DiscoverySuggestion } from "@/types/vigla";
import { haversine } from "@/lib/geo";

export const DISCOVERY: DiscoverySuggestion[] = [
  {
    id: "cormet-roselend",
    title: "Cormet de Roselend",
    region: "Alpes",
    distanceKm: 65,
    durationMin: 110,
    description: "Col mythique reliant Beaufort à Bourg-Saint-Maurice, virages roulants et vues sur le lac.",
    origin: { lat: 45.7213, lng: 6.5722 },
    destination: { lat: 45.6215, lng: 6.7695 },
  },
  {
    id: "route-des-cretes",
    title: "Route des Crêtes",
    region: "Vosges",
    distanceKm: 77,
    durationMin: 140,
    description: "Panoramas ouverts, virages nets, une des plus belles routes des Vosges.",
    origin: { lat: 47.9066, lng: 7.0872 },
    destination: { lat: 47.7906, lng: 7.1044 },
  },
  {
    id: "gorges-verdon",
    title: "Gorges du Verdon",
    region: "Provence",
    distanceKm: 95,
    durationMin: 180,
    description: "Corniche sublime au-dessus du canyon, sinueux et technique.",
    origin: { lat: 43.7519, lng: 6.3103 },
    destination: { lat: 43.7625, lng: 6.5389 },
  },
  {
    id: "presquile-crozon",
    title: "Presqu'île de Crozon",
    region: "Bretagne",
    distanceKm: 55,
    durationMin: 100,
    description: "Falaises, phares, petits ports — boucle bretonne iodée.",
    origin: { lat: 48.2496, lng: -4.4881 },
    destination: { lat: 48.2496, lng: -4.4881 },
  },
  {
    id: "gorges-tarn",
    title: "Gorges du Tarn",
    region: "Massif Central",
    distanceKm: 85,
    durationMin: 165,
    description: "Falaises calcaires, villages perchés, ambiance canyon.",
    origin: { lat: 44.3572, lng: 3.2214 },
    destination: { lat: 44.2044, lng: 3.5911 },
  },
  {
    id: "col-turini",
    title: "Col de Turini",
    region: "Alpes-Maritimes",
    distanceKm: 45,
    durationMin: 80,
    description: "Rallye Monte-Carlo, épingles infinies, pinèdes.",
    origin: { lat: 43.9067, lng: 7.2933 },
    destination: { lat: 43.9928, lng: 7.3781 },
  },
  {
    id: "route-des-sapins",
    title: "Route des Sapins",
    region: "Jura",
    distanceKm: 42,
    durationMin: 75,
    description: "Forêts jurassiennes, virages tranquilles.",
    origin: { lat: 46.7833, lng: 5.9333 },
    destination: { lat: 46.6667, lng: 6.05 },
  },
  {
    id: "ballon-alsace",
    title: "Ballon d'Alsace",
    region: "Vosges",
    distanceKm: 48,
    durationMin: 90,
    description: "Ascension pure et panoramas frontière.",
    origin: { lat: 47.8181, lng: 6.8408 },
    destination: { lat: 47.8248, lng: 6.8306 },
  },
  {
    id: "col-madeleine",
    title: "Col de la Madeleine",
    region: "Savoie",
    distanceKm: 60,
    durationMin: 120,
    description: "Grand col alpin, alpages, dénivelé sérieux.",
    origin: { lat: 45.4372, lng: 6.4136 },
    destination: { lat: 45.4272, lng: 6.4111 },
  },
  {
    id: "cotes-armor",
    title: "Côtes d'Armor",
    region: "Bretagne",
    distanceKm: 70,
    durationMin: 130,
    description: "Rose granit, petits ports, virages côtiers.",
    origin: { lat: 48.65, lng: -3.45 },
    destination: { lat: 48.65, lng: -3.45 },
  },
  {
    id: "cevennes",
    title: "Cévennes — Mont Aigoual",
    region: "Occitanie",
    distanceKm: 88,
    durationMin: 170,
    description: "Cols oubliés, forêts, silence.",
    origin: { lat: 44.1214, lng: 3.5811 },
    destination: { lat: 44.121, lng: 3.5817 },
  },
  {
    id: "col-galibier",
    title: "Col du Galibier",
    region: "Alpes",
    distanceKm: 72,
    durationMin: 150,
    description: "Le géant, 2645m, virages majestueux.",
    origin: { lat: 45.0644, lng: 6.4083 },
    destination: { lat: 45.0644, lng: 6.4083 },
  },
  {
    id: "pyrenees-tourmalet",
    title: "Col du Tourmalet",
    region: "Pyrénées",
    distanceKm: 68,
    durationMin: 135,
    description: "Icône pyrénéenne, montée régulière et sauvage.",
    origin: { lat: 42.9081, lng: 0.1414 },
    destination: { lat: 42.9081, lng: 0.1414 },
  },
  {
    id: "loire-chateaux",
    title: "Vallée de la Loire",
    region: "Centre",
    distanceKm: 95,
    durationMin: 140,
    description: "Route douce entre châteaux et bord de Loire.",
    origin: { lat: 47.3936, lng: 0.6892 },
    destination: { lat: 47.5936, lng: 1.3336 },
  },
  {
    id: "corse-cap-corse",
    title: "Cap Corse",
    region: "Corse",
    distanceKm: 110,
    durationMin: 210,
    description: "Boucle mer/montagne, virages permanents.",
    origin: { lat: 42.7, lng: 9.45 },
    destination: { lat: 42.7, lng: 9.45 },
  },
];

export function suggestionsNear(lat: number, lng: number, limit = 6): DiscoverySuggestion[] {
  return DISCOVERY.map((s) => ({
    s,
    d: haversine(lat, lng, s.origin.lat, s.origin.lng),
  }))
    .sort((a, b) => a.d - b.d)
    .slice(0, limit)
    .map((x) => x.s);
}
